openapi: 3.0.0
info:
  title: Definitions
  version: 1.0.0
paths: {}

components:
  parameters:
    # Paging offset
    OffsetParam:
      name: offset
      required: false
      in: query
      description: Paging offset
      schema:
        type: integer
        minimum: 0
        multipleOf: 10
        default: 0
    # Page size
    LimitParam:
      name: limit
      required: false
      in: query
      description: Paging limit
      schema:
        type: integer
        minimum: 10
        maximum: 1000
        multipleOf: 10
        default: 20
  schemas:
    Task:
      allOf:
        - $ref: '#/components/schemas/CreateTask'
        - type: object
          properties:
            id: 
              type: integer
          required:
            - id
    CreateTask:
      type: object
      properties:
        status:
          type: string
        name: 
          type: string
      required:
        - name
        - status
    SetStatus:
      type: object
      properties:
        status:
          type: string
        id: 
          type: integer
      required:
        - id
        - status