openapi: 3.0.1
info:
  title: NewSite Rest API
  description: Categories
  version: 1.0.0
paths:
  /tasks/:
    get:
      tags:
        - Task
      summary: All available tasks
      responses:
        200:
          description: A list of categories.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "difinitions.yaml#/components/schemas/Task"

    post:
      tags:
        - Task
      summary: Add a new Task
      requestBody:
        description: Task create request
        content:
          application/json:
            schema:
              $ref: "difinitions.yaml#/components/schemas/CreateTask"
        required: true
      responses:
        201:
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "difinitions.yaml#/components/schemas/Task"

    patch:
      tags:
        - Task
      summary: Update Task
      requestBody:
        description: Task update request
        content:
          application/json:
            schema:
              $ref: "difinitions.yaml#/components/schemas/Task"
        required: true
      responses:
        200:
          description: Successful operation

  /tasks/{id}:
    delete:
      tags:
        - Task
      summary: Delete Task
      parameters:
        - in: path
          name: id
          required: true
          schema: 
            type: integer
          description: News delete request
      responses:
        200:
          description: Successful operation

  /tasks/setStatus/:
    post:
      tags:
        - Task
      summary: Set status
      requestBody:
        description: Set status request
        content:
            application/json:
              schema:
                $ref: "difinitions.yaml#/components/schemas/SetStatus"
        required: true
      responses:
        200:
          description: Successful operation